### ISSUE TITLE
Replicability package not accessible

### ISSUE THREAD

**Issue by ysmartin** [SNTSVV/SMRL#1]
According to the website
> We provide the whole SMRL toolset in a replicability package available at http://bit.ly/SMRL2020

However, that URL forwards to the address of a Google Drive folder which returns a 404 error page. (As a minor issue, the URL appears as plaintext, rather than as a hyperlink).

**Comment by pastoref** [comment]
Thanks for pointing it out. I just put it on zenodo. Don't hesitate to contact me if it does not work as expected.

https://zenodo.org/record/4752931 
(https://doi.org/10.5281/zenodo.4752931)
